In [1]:
import pandas as pd
import numpy as np

In [7]:
df=pd.read_csv(r"C:\Users\Prakash\Downloads\employee_list\Employee.csv")

In [13]:
df.head()

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1

In [14]:
df.tail()

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
4648,Bachelors,2013,Bangalore,3,26,Female,No,4,0
4649,Masters,2013,Pune,2,37,Male,No,2,1
4650,Masters,2018,New Delhi,3,27,Male,No,5,1
4651,Bachelors,2012,Bangalore,3,30,Male,Yes,2,0
4652,Bachelors,2015,Bangalore,3,33,Male,Yes,4,0

In [16]:
df.shape

(4653, 9)

In [17]:
df.columns

Index(['Education', 'JoiningYear', 'City', 'PaymentTier', 'Age', 'Gender',
       'EverBenched', 'ExperienceInCurrentDomain', 'LeaveOrNot'],
      dtype='str')

In [18]:
df.dtypes

Education                      str
JoiningYear                  int64
City                           str
PaymentTier                  int64
Age                          int64
Gender                         str
EverBenched                    str
ExperienceInCurrentDomain    int64
LeaveOrNot                   int64
dtype: object

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4653 entries, 0 to 4652
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Education                  4653 non-null   str
 1   JoiningYear                4653 non-null   int64
 2   City                       4653 non-null   str
 3   PaymentTier                4653 non-null   int64
 4   Age                        4653 non-null   int64
 5   Gender                     4653 non-null   str
 6   EverBenched                4653 non-null   str
 7   ExperienceInCurrentDomain  4653 non-null   int64
 8   LeaveOrNot                 4653 non-null   int64
dtypes: int64(5), str(4)
memory usage: 327.3 KB

In [20]:
df.describe()

,JoiningYear,PaymentTier,Age,ExperienceInCurrentDomain,LeaveOrNot
count,4653.000000,4653.000000,4653.000000,4653.000000,4653.000000
mean,2015.062970,2.698259,29.393295,2.905652,0.343864
std,1.863377,0.561435,4.826087,1.558240,0.475047
min,2012.000000,1.000000,22.000000,0.000000,0.000000
25%,2013.000000,3.000000,26.000000,2.000000,0.000000
50%,2015.000000,3.000000,28.000000,3.000000,0.000000
75%,2017.000000,3.000000,32.000000,4.000000,1.000000
max,2018.000000,3.000000,41.000000,7.000000,1.000000

In [21]:
df["Age"].mean()

np.float64(29.393294648613796)

In [22]:
df["Age"].median()

np.float64(28.0)

In [24]:
df["Age"].mode()

0    26
Name: Age, dtype: int64

In [25]:
df["Age"].var()

np.float64(23.29111581965536)

In [26]:
df["Age"].std()

np.float64(4.826087009126065)

In [27]:
df["Age"].min()

np.int64(22)

In [28]:
df["Age"].max()

np.int64(41)

In [29]:
df["Age"].count()

np.int64(4653)

In [30]:
df["City"].unique()

<StringArray>
['Bangalore', 'Pune', 'New Delhi']
Length: 3, dtype: str

In [31]:
df["City"].nunique()

3

In [32]:
df["City"].value_counts()

City
Bangalore    2228
Pune         1268
New Delhi    1157
Name: count, dtype: int64

In [33]:
df.isnull()

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
4648,False,False,False,False,False,False,False,False,False
4649,False,False,False,False,False,False,False,False,False
4650,False,False,False,False,False,False,False,False,False
4651,False,False,False,False,False,False,False,False,False
4652,False,False,False,False,False,False,False,False,False

In [34]:
df.isnull().sum()

Education                    0
JoiningYear                  0
City                         0
PaymentTier                  0
Age                          0
Gender                       0
EverBenched                  0
ExperienceInCurrentDomain    0
LeaveOrNot                   0
dtype: int64

In [35]:
df.isnull().mean()*100

Education                    0.0
JoiningYear                  0.0
City                         0.0
PaymentTier                  0.0
Age                          0.0
Gender                       0.0
EverBenched                  0.0
ExperienceInCurrentDomain    0.0
LeaveOrNot                   0.0
dtype: float64

In [36]:
df.dropna()

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1
...,...,...,...,...,...,...,...,...,...
4648,Bachelors,2013,Bangalore,3,26,Female,No,4,0
4649,Masters,2013,Pune,2,37,Male,No,2,1
4650,Masters,2018,New Delhi,3,27,Male,No,5,1
4651,Bachelors,2012,Bangalore,3,30,Male,Yes,2,0
4652,Bachelors,2015,Bangalore,3,33,Male,Yes,4,0

In [37]:
df.fillna(0)

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1
...,...,...,...,...,...,...,...,...,...
4648,Bachelors,2013,Bangalore,3,26,Female,No,4,0
4649,Masters,2013,Pune,2,37,Male,No,2,1
4650,Masters,2018,New Delhi,3,27,Male,No,5,1
4651,Bachelors,2012,Bangalore,3,30,Male,Yes,2,0
4652,Bachelors,2015,Bangalore,3,33,Male,Yes,4,0

In [38]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
4648     True
4649    False
4650    False
4651    False
4652     True
Length: 4653, dtype: bool

In [39]:
df.duplicated().sum()

np.int64(1889)

In [40]:
df.drop_duplicates()

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1
...,...,...,...,...,...,...,...,...,...
4645,Masters,2017,Pune,2,31,Female,No,2,0
4647,Bachelors,2016,Pune,3,30,Male,No,2,0
4649,Masters,2013,Pune,2,37,Male,No,2,1
4650,Masters,2018,New Delhi,3,27,Male,No,5,1
4651,Bachelors,2012,Bangalore,3,30,Male,Yes,2,0

In [41]:
df["Age"]

0       34
1       28
2       38
3       27
4       24
        ..
4648    26
4649    37
4650    27
4651    30
4652    33
Name: Age, Length: 4653, dtype: int64

In [42]:
df[["Age","PaymentTier"]]

      Age  PaymentTier
0      34            3
1      28            1
2      38            3
3      27            3
4      24            3
...   ...          ...
4648   26            3
4649   37            2
4650   27            3
4651   30            3
4652   33            3

[4653 rows x 2 columns]

In [43]:
df.iloc[0:5]

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1

In [44]:
df[df["Age"]>30]

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
6,Bachelors,2015,New Delhi,3,38,Male,No,0,0
7,Bachelors,2016,Bangalore,3,34,Female,No,2,1
9,Masters,2017,New Delhi,2,37,Male,No,2,0
...,...,...,...,...,...,...,...,...,...
4643,Bachelors,2013,Bangalore,3,31,Female,No,5,0
4644,Bachelors,2015,Pune,3,32,Female,Yes,1,1
4645,Masters,2017,Pune,2,31,Female,No,2,0
4649,Masters,2013,Pune,2,37,Male,No,2,1
4652,Bachelors,2015,Bangalore,3,33,Male,Yes,4,0

In [45]:
df.sort_values("Age")

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
4069,Masters,2013,New Delhi,2,22,Male,Yes,0,1
4539,Bachelors,2014,Bangalore,3,22,Female,No,0,0
4048,Bachelors,2014,Bangalore,3,22,Male,No,0,0
4070,Bachelors,2015,Pune,1,22,Female,No,0,1
4561,Bachelors,2013,Bangalore,3,22,Male,No,0,1
...,...,...,...,...,...,...,...,...,...
3394,Bachelors,2013,Bangalore,3,41,Male,No,2,0
3355,Bachelors,2016,Bangalore,3,41,Male,No,4,0
3500,Bachelors,2017,Bangalore,3,41,Male,No,1,0
3527,Bachelors,2017,New Delhi,3,41,Male,No,2,0
3386,Masters,2013,Pune,2,41,Male,No,2,1

In [46]:
df.rename(columns={"Age":"Age_Years"})

,Education,JoiningYear,City,PaymentTier,Age_Years,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1
...,...,...,...,...,...,...,...,...,...
4648,Bachelors,2013,Bangalore,3,26,Female,No,4,0
4649,Masters,2013,Pune,2,37,Male,No,2,1
4650,Masters,2018,New Delhi,3,27,Male,No,5,1
4651,Bachelors,2012,Bangalore,3,30,Male,Yes,2,0
4652,Bachelors,2015,Bangalore,3,33,Male,Yes,4,0

In [50]:
df["Bonus"]=df["PaymentTier"]*0.10

In [51]:
df.drop("Bonus",axis=1)

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1
...,...,...,...,...,...,...,...,...,...
4648,Bachelors,2013,Bangalore,3,26,Female,No,4,0
4649,Masters,2013,Pune,2,37,Male,No,2,1
4650,Masters,2018,New Delhi,3,27,Male,No,5,1
4651,Bachelors,2012,Bangalore,3,30,Male,Yes,2,0
4652,Bachelors,2015,Bangalore,3,33,Male,Yes,4,0

In [52]:
df.groupby("JoiningYear")

In [53]:
df.groupby("JoiningYear")["PaymentTier"].mean()

JoiningYear
2012    2.831349
2013    2.732436
2014    2.789700
2015    2.603073
2016    2.840000
2017    2.490072
2018    2.907357
Name: PaymentTier, dtype: float64

In [55]:
df1=df[df["JoiningYear"]==2012]
df2=df[df["JoiningYear"]==2013]

In [56]:
pd.concat([df1,df2])

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot,Bonus
10,Masters,2012,Bangalore,3,27,Male,No,5,1,0.3
14,Bachelors,2012,Bangalore,3,37,Male,No,4,0,0.3
20,Bachelors,2012,Bangalore,3,37,Male,No,0,0,0.3
36,Bachelors,2012,New Delhi,3,29,Male,No,3,0,0.3
46,PHD,2012,New Delhi,3,27,Male,No,5,0,0.3
...,...,...,...,...,...,...,...,...,...,...
4638,Bachelors,2013,Bangalore,3,26,Male,No,4,0,0.3
4643,Bachelors,2013,Bangalore,3,31,Female,No,5,0,0.3
4646,Bachelors,2013,Bangalore,3,25,Female,No,3,0,0.3
4648,Bachelors,2013,Bangalore,3,26,Female,No,4,0,0.3
4649,Masters,2013,Pune,2,37,Male,No,2,1,0.2

In [58]:
pd.merge(df1,df2,on="LeaveOrNot")

,Education_x,JoiningYear_x,City_x,PaymentTier_x,Age_x,Gender_x,EverBenched_x,ExperienceInCurrentDomain_x,LeaveOrNot,Bonus_x,Education_y,JoiningYear_y,City_y,PaymentTier_y,Age_y,Gender_y,EverBenched_y,ExperienceInCurrentDomain_y,Bonus_y
0,Masters,2012,Bangalore,3,27,Male,No,5,1,0.3,Bachelors,2013,Pune,1,28,Female,No,3,0.1
1,Masters,2012,Bangalore,3,27,Male,No,5,1,0.3,Bachelors,2013,Pune,2,31,Female,No,2,0.2
2,Masters,2012,Bangalore,3,27,Male,No,5,1,0.3,Bachelors,2013,Bangalore,3,30,Male,No,3,0.3
3,Masters,2012,Bangalore,3,27,Male,No,5,1,0.3,PHD,2013,Bangalore,2,25,Male,No,3,0.2
4,Masters,2012,Bangalore,3,27,Male,No,5,1,0.3,Bachelors,2013,Bangalore,3,31,Female,No,0,0.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200186,Bachelors,2012,Bangalore,3,30,Male,Yes,2,0,0.3,Bachelors,2013,Bangalore,3,39,Female,No,5,0.3
200187,Bachelors,2012,Bangalore,3,30,Male,Yes,2,0,0.3,Bachelors,2013,Bangalore,3,26,Male,No,4,0.3
200188,Bachelors,2012,Bangalore,3,30,Male,Yes,2,0,0.3,Bachelors,2013,Bangalore,3,31,Female,No,5,0.3
200189,Bachelors,2012,Bangalore,3,30,Male,Yes,2,0,0.3,Bachelors,2013,Bangalore,3,25,Female,No,3,0.3
200190,Bachelors,2012,Bangalore,3,30,Male,Yes,2,0,0.3,Bachelors,2013,Bangalore,3,26,Female,No,4,0.3