In [3]:
import pandas as pd
df=pd.read_csv(r"C:\Users\Prakash\Downloads\diabete_prediction_dataset\diabetes_prediction_dataset.csv")

In [4]:
df

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0
...,...,...,...,...,...,...,...,...,...
99995,Female,80.0,0,0,No Info,27.32,6.2,90,0
99996,Female,2.0,0,0,No Info,17.37,6.5,100,0
99997,Male,66.0,0,0,former,27.83,5.7,155,0
99998,Female,24.0,0,0,never,35.42,4.0,100,0
99999,Female,57.0,0,0,current,22.43,6.6,90,0

In [5]:
df.tail()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
99995,Female,80.0,0,0,No Info,27.32,6.2,90,0
99996,Female,2.0,0,0,No Info,17.37,6.5,100,0
99997,Male,66.0,0,0,former,27.83,5.7,155,0
99998,Female,24.0,0,0,never,35.42,4.0,100,0
99999,Female,57.0,0,0,current,22.43,6.6,90,0

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   gender               100000 non-null  str
 1   age                  100000 non-null  float64
 2   hypertension         100000 non-null  int64
 3   heart_disease        100000 non-null  int64
 4   smoking_history      100000 non-null  str
 5   bmi                  100000 non-null  float64
 6   HbA1c_level          100000 non-null  float64
 7   blood_glucose_level  100000 non-null  int64
 8   diabetes             100000 non-null  int64
dtypes: float64(3), int64(4), str(2)
memory usage: 6.9 MB

In [7]:
df.describe()

,age,hypertension,heart_disease,bmi,HbA1c_level,blood_glucose_level,diabetes
count,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,41.885856,0.07485,0.039420,27.320767,5.527507,138.058060,0.085000
std,22.516840,0.26315,0.194593,6.636783,1.070672,40.708136,0.278883
min,0.080000,0.00000,0.000000,10.010000,3.500000,80.000000,0.000000
25%,24.000000,0.00000,0.000000,23.630000,4.800000,100.000000,0.000000
50%,43.000000,0.00000,0.000000,27.320000,5.800000,140.000000,0.000000
75%,60.000000,0.00000,0.000000,29.580000,6.200000,159.000000,0.000000
max,80.000000,1.00000,1.000000,95.690000,9.000000,300.000000,1.000000

In [8]:
df.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0

In [9]:
df.head(10)

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0
5,Female,20.0,0,0,never,27.32,6.6,85,0
6,Female,44.0,0,0,never,19.31,6.5,200,1
7,Female,79.0,0,0,No Info,23.86,5.7,85,0
8,Male,42.0,0,0,never,33.64,4.8,145,0
9,Female,32.0,0,0,never,27.32,5.0,100,0

In [10]:
df.tail(20)

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
99980,Female,52.0,0,0,never,27.32,6.1,145,0
99981,Male,26.0,0,0,No Info,24.08,5.8,90,0
99982,Female,80.0,0,0,never,30.04,6.0,126,0
99983,Female,21.0,0,0,No Info,27.32,5.7,126,0
99984,Male,80.0,1,0,No Info,20.96,6.6,85,0
99985,Male,25.0,0,0,No Info,27.32,5.8,145,0
99986,Female,63.0,0,0,never,29.01,4.8,145,0
99987,Female,23.0,0,0,never,17.87,5.8,100,0
99988,Male,19.0,0,0,No Info,25.75,5.0,145,0
99989,Female,26.0,0,0,No Info,27.32,5.0,158,0
99990,Male,39.0,0,0,No Info,27.32,6.1,100,0
99991,Male,22.0,0,0,current,29.65,6.0,80,0
99992,Female,26.0,0,0,never,34.34,6.5,160,0
99993,Female,40.0,0,0,never,40.69,3.5,155,0
99994,Female,36.0,0,0,No Info,24.60,4.8,145,0
99995,Female,80.0,0,0,No Info,27.32,6.2,90,0
99996,Female,2.0,0,0,No Info,17.37,6.5,100,0
99997,Male,66.0,0,0,former,27.83,5.7,155,0
99998,Female,24.0,0,0,never,35.42,4.0,100,0
99999,Female,57.0,0,0,current,22.43,6.6,90,0

In [12]:
df.shape

(100000, 9)

In [13]:
df.columns

Index(['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history',
       'bmi', 'HbA1c_level', 'blood_glucose_level', 'diabetes'],
      dtype='str')

In [14]:
df.index

RangeIndex(start=0, stop=100000, step=1)

In [15]:
df.age

0        80.0
1        54.0
2        28.0
3        36.0
4        76.0
         ...
99995    80.0
99996     2.0
99997    66.0
99998    24.0
99999    57.0
Name: age, Length: 100000, dtype: float64

In [16]:
df["bmi"].unique()

array([25.19, 27.32, 23.45, ..., 59.42, 44.39, 60.52], shape=(4247,))

In [17]:
df.value_counts()

gender  age   hypertension  heart_disease  smoking_history  bmi    HbA1c_level  blood_glucose_level  diabetes
Female  80.0  0             0              No Info          27.32  6.5          159                  0           9
                                                                   6.2          90                   0           9
                                                                   4.0          85                   0           8
                                                                                160                  0           7
                                                                                158                  0           7
                                                                                                                ..
        36.0  0             0              No Info          24.60  4.8          145                  0           1
        2.0   0             0              No Info          17.37  6.5          100                  0           1
Male    66.0  0             0              former           27.83  5.7          155                  0           1
Female  24.0  0             0              never            35.42  4.0          100                  0           1
        57.0  0             0              current          22.43  6.6          90                   0           1
Name: count, Length: 96146, dtype: int64

In [18]:
df["age"].mean()

np.float64(41.885856)

In [19]:
df["age"].median()

np.float64(43.0)

In [20]:
df["age"].min()

np.float64(0.08)

In [21]:
df["blood_glucose_level"].mean()

np.float64(138.05806)

In [22]:
df["blood_glucose_level"].median()

np.float64(140.0)

In [23]:
df["blood_glucose_level"].max()

np.int64(300)

In [24]:
df["age"].max()

np.float64(80.0)

In [25]:
df.dtypes

gender                     str
age                    float64
hypertension             int64
heart_disease            int64
smoking_history            str
bmi                    float64
HbA1c_level            float64
blood_glucose_level      int64
diabetes                 int64
dtype: object

In [26]:
df.drop_duplicates()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0
...,...,...,...,...,...,...,...,...,...
99994,Female,36.0,0,0,No Info,24.60,4.8,145,0
99996,Female,2.0,0,0,No Info,17.37,6.5,100,0
99997,Male,66.0,0,0,former,27.83,5.7,155,0
99998,Female,24.0,0,0,never,35.42,4.0,100,0
99999,Female,57.0,0,0,current,22.43,6.6,90,0

In [28]:
df.size

900000

In [29]:
df.ndim

2

In [30]:
df.empty

False

In [31]:
df.sample(10)

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
12044,Female,39.00,0,0,never,25.39,4.5,155,0
22128,Male,61.00,1,0,never,28.19,6.0,155,0
67183,Female,11.00,0,0,No Info,15.82,6.2,100,0
61601,Female,9.00,0,0,No Info,20.93,4.0,90,0
1475,Female,1.56,0,0,No Info,17.28,5.8,155,0
2169,Female,42.00,0,0,ever,41.39,6.2,280,1
96687,Female,53.00,0,0,No Info,24.03,6.0,140,0
8407,Female,75.00,0,0,never,28.81,6.1,80,0
28395,Female,54.00,0,0,never,19.21,6.2,130,0
45345,Male,13.00,0,0,No Info,16.71,6.2,159,0

In [32]:
df['age'].describe()

count    100000.000000
mean         41.885856
std          22.516840
min           0.080000
25%          24.000000
50%          43.000000
75%          60.000000
max          80.000000
Name: age, dtype: float64